apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dirgim-test-project
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/kpavic-tenant/dirgim-test-project/dirgim-test-project@sha256:c9d193ebbdcefad11d4b7dbb6c98f8e05fde918d9992bd3cb52da7266110d984
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
